### ISSUE TITLE
Markdown formatter leaves macros identifiers in the output

### ISSUE THREAD

**Issue by bweir** [cdosborn/lit#13]
The source text

	Some interesting comments

	    << * >>=
	    OBJ
		lcd : "LameLCD"
		gfx : "LameGFX"
	    
	    PUB SinglePixel
		lcd.Start(gfx.Start)
		gfx.Sprite(@data, 0,0, 0)
		lcd.DrawScreen
		
	    DAT
	    
	    data
	    word    0
	    word    8, 8
	    word    %%00011000
	    word    %%01111110
	    word    %%01100110
	    word    %%11000011
	    word    %%11000011
	    word    %%01100110
	    word    %%01111110
	    word    %%00011000
	    
The output:

	Some interesting comments

	```
	<< * >>=
	OBJ
	    lcd : "LameLCD"
	    gfx : "LameGFX"

	PUB SinglePixel
	    lcd.Start(gfx.Start)
	    gfx.Sprite(@data, 0,0, 0)
	    lcd.DrawScreen
	    
	DAT

	data
	word    0
	word    8, 8
	word    %%00011000
	word    %%01111110
	word    %%01100110
	word    %%11000011
	word    %%11000011
	word    %%01100110
	word    %%01111110
	word    %%00011000

	```

Am I doing something wrong?

**Comment by bweir** [comment]
Also, is there any way to use the macros to include a section of code multiple times in the markdown output but not in the source code output?

**Comment by bweir** [comment]
I should also mention that I'm completely excited that this program exists at all because I have a massive collection of demo programs for a system I'm developing that I have not found a sane way to document and this seems like the option with the best prospects to date!

**Comment by cdosborn** [comment]
That is basic generated markdown. Markdown generation is a convenience but not great for several reasons. The intent of lit is to have a legible code format with comments (.lit) and then have pretty documentation (.html) while being able to generate the executable. Read [here](http://cdosborn.github.io/lit/lit/lit.hs.html) for an example. With the html, you get hyperlinks to the different macro definitions.
