### ISSUE TITLE
Codegen whitespace changes seem to have broken output

### ISSUE THREAD

**Issue by tcrs** [cdosborn/lit#14]
I'm still slowly working away on some local changes I have to lit (includes & line directives), and have just rebased up to the latest master. I've found that the code generation doesn't seem to work properly any more, a simple test case is this:
```
    << * >>=
    some text
    << a >>
    << b >>

    << a >>=
    text2

    << b >>=
    text3
```
Which generates
```
text2

text3

some text
```
with current master, but
```

some text
text2

text3
```
with older versions (I bisected it down to 1d2837c87a4d89b3a42b5218fe30a459cc47b1f8).

I've not had much time to look at this so it's possible that it's user error on my part.

**Comment by cdosborn** [comment]
Thanks for the headsup!

**Comment by tcrs** [comment]
I have another testcase for you; try this:
```
	<<*>>=
		<< a >>
			<< a >>

	<<a>>=
	line one
	line two
```
latest master gives:
```
	line one
line two

		line one
line two
```
older version gives:
```
	line one
	line two

		line one
		line two


```
I think this is because multiple code lines are now appended together before being substituted into the output, so ```Code txt -> T.append baseIndent txt``` only appends the indent to the first line in a code block. Replacing it with this rather horrible construction ```Code txt -> T.append baseIndent $ T.replace (T.pack "\n") (T.append (T.pack "\n") baseIndent) txt``` does appear to fix it. I'm fairly sure there's a nicer way to structure that but don't really have time to look at it right now, so thought I'd give you a heads up!

**Comment by tcrs** [comment]
(Oh I assumed commenting in this issue would re-open it)

**Comment by cdosborn** [comment]
Thanks again. Take a look at the `test/`. Lit no longer intersperses newlines, it adds only the whitespace the user provides. Also, It's now super easy to run/add tests.
